// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniBlog.Data;

namespace MiniBlog.Data.Migrations
{
    [DbContext(typeof(MiniBlogDbContext))]
    partial class MiniBlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MiniBlog.Data.Entity.AdminEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateTime = new DateTime(2020, 5, 6, 18, 50, 8, 16, DateTimeKind.Local).AddTicks(8750),
                            Password = "123456",
                            UpdateTime = new DateTime(2020, 5, 6, 18, 50, 8, 18, DateTimeKind.Local).AddTicks(6987),
                            User = "admin"
                        });
                });

            modelBuilder.Entity("MiniBlog.Data.Entity.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Category1",
                            CreateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9210),
                            UpdateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9236)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Category2",
                            CreateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9300),
                            UpdateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9302)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Category3",
                            CreateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9305),
                            UpdateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9306)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Category4",
                            CreateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9309),
                            UpdateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9310)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Category5",
                            CreateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9312),
                            UpdateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9313)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Category6",
                            CreateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9321),
                            UpdateTime = new DateTime(2020, 5, 6, 18, 50, 8, 30, DateTimeKind.Local).AddTicks(9323)
                        });
                });

            modelBuilder.Entity("MiniBlog.Data.Entity.PictureEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Big")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Origin")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("Small")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("MiniBlog.Data.Entity.PostEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<bool>("IsShow")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Summary")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("MiniBlog.Data.Entity.PostEntity", b =>
                {
                    b.HasOne("MiniBlog.Data.Entity.CategoryEntity", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
